### ISSUE TITLE
Download all on Season only downloads last episode

### ISSUE THREAD

**Issue by b-m-f** [jellyfin/jellyfin-android#1497]
### Describe the bug

1. Go to season overview
2. Click on 3 dots
3. Press download all
4. Only the last episode is downloaded

I have noticed that this happens on seasons where no episode is watched. It worked on a season with 3 episodes, where the first one was marked as watched.

### Application version

2.6.2

### Where did you install the app from?

F-Droid

### Device information

Pixel Tablet

### Android version

GrapheneOS latest

### Jellyfin server version

10.9.11

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by street-grease-coder** [comment]
This was fixed in the web version on case of use and/or similar solution applies

https://github.com/jellyfin/jellyfin-web/issues/5672

**Comment by b-m-f** [comment]
Problem still persists with latest version

**Comment by BRUHItsABunny** [comment]
Yup problem still here..

**Comment by RPDJF** [comment]
Yup these guys aren't lying

**Comment by SlothGod** [comment]
Problem still exists. Xiaomi 14T Pro running HyperOS 2.0.225.0 Android 16. Press download all on a show with 9 episodes, downloads episode 3 & 9.
