### ISSUE TITLE
App crashes when casting

### ISSUE THREAD

**Issue by AlessandroTischer** [jellyfin/jellyfin-android#1679]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-android/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

When I try to cast to my chromecast and my pc (where jellyfin webpage is open) via jellyfin android app on my (aosp based rom) Android 15 phone the Jellyfin page is displayed on the tv, but as soon as I start playing anything (both on chromecast and pc), the app crashes. Using an Android 14 Xiaomi stock phone, it gets to cast and keeps working (though the casting control bar on the bottom quickly disappears). No other app has any problem casting from my A15 phone.

I collected some catlogs while trying to cast to my pc, but i'm not sure if they contain useful data, sorry...

[logcat_2025-06-15_12-16-38.txt](https://github.com/user-attachments/files/20745010/logcat_2025-06-15_12-16-38.txt)

### Logs

```shell

```

### Application version

2.6.3

### Where did you install the app from?

Google Play Store

### Device information

Xiaomi Mi 9T

### Android version

Android 15 - Infinity X 

### Jellyfin server version

10.10.7

**Comment by StijnClaessens** [comment]
I want to report the same issue:

- as soon as I start casting from the Android app, the app crashes. Casting continues but can't be controlled anymore from the app.
- when I restart the app, it doesn't find the Google casting devices anymore. This can only be resolved by clearing the app's storage via the phones settings menu. Clearing the app's cache does not help.

- Jellyfin server: 10.10.7 on Windows
- Jellyfin android: 2.6.3 (installed from Google Play store)
- phone: Google Pixel 9 - Android 16
- Google cast device: Google Chromecast audio - firmware 1.56.467166

**Comment by wjtk4444** [comment]
Same (I think) issue, tried 2.6.3 as well as last 2.5.x and the latest beta. Stacktrace in case it's helpful. I think it happens when a media playback notification is being created, but I tried blocking app's notification in every way imaginable trough settings and adb but to no avail. Still crashes.

```
time: 1768581212509
msg: java.lang.IllegalStateException: Can't copy a recycled bitmap
stacktrace: java.lang.IllegalStateException: Can't copy a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:429)
	at android.graphics.Bitmap.copy(Bitmap.java:725)
	at android.graphics.drawable.Icon.setBitmap(Icon.java:200)
	at android.graphics.drawable.Icon.createWithBitmap(Icon.java:833)
	at android.app.Notification$Builder.setLargeIcon(Notification.java:5228)
	at org.jellyfin.mobile.webapp.RemotePlayerService$notify$1.invokeSuspend(SourceFile:614)
	at U4.a.resumeWith(SourceFile:9)
	at s5.p.o(SourceFile:7)
	at n5.a.resumeWith(SourceFile:23)
	at U4.a.resumeWith(SourceFile:32)
	at n5.M.run(SourceFile:107)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [s0{Cancelling}@dd6dd22, Dispatchers.Main]
```

**Comment by JordanMunroe** [comment]
Also having this issue. Server version 10.11.5 and the latest android app on Pixel 9. It also crashes when I load the app while something is playing. The bottom control bar briefly pops up and then it crashes.
I can exit the media on my media center pc and the android app loads fine until I play something again.

Definitely seems to be related to the media control bar at the bottom of the app.

**Comment by starfoxdot64** [comment]
Hi! I have this issue as well. 
- Pixel 8 Pro, Android 17 Beta (CP21.260306.017)
- Jellyfin client is current (Play Store, as of 04/04/2026)
- Server 10.11.6

Repro:
- Log into client
- Start casting to device (optional, same outcome)
- Begin playback of a music track (tested: FLAC, MP3)

Stacktrace:
```
--------- beginning of crash
04-05 20:39:07.967 19790 19790 E AndroidRuntime: FATAL EXCEPTION: main
04-05 20:39:07.967 19790 19790 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 19790
04-05 20:39:07.967 19790 19790 E AndroidRuntime: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:732)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:82)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:166)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.graphics.Canvas.drawBitmap(Canvas.java:1640)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.graphics.Bitmap.createScaledAshmemBitmap(Bitmap.java:989)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:1019)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.media.MediaMetadata$Builder.build(MediaMetadata.java:1002)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.media.session.MediaSession.setMetadata(MediaSession.java:613)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at org.jellyfin.mobile.webapp.RemotePlayerService$notify$1.invokeSuspend(SourceFile:359)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at S5.a.resumeWith(SourceFile:9)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at q6.p.q(SourceFile:7)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at l6.a.resumeWith(SourceFile:23)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at S5.a.resumeWith(SourceFile:32)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at l6.M.run(SourceFile:107)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:1095)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.os.Handler.dispatchMessageImpl(Handler.java:135)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:125)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:292)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:393)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:9486)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
04-05 20:39:07.967 19790 19790 E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [s0{Cancelling}@8ea3ee5, Dispatchers.Main]
```

**Comment by Yamus08** [comment]
Same issue here. First time attempting since updating to official Android 17 on Pixel 9 Pro XK

**Comment by Uncia60** [comment]
Also having the same issue since upgrading my Pixel 7a to Android 17.

**Comment by nielsvanvelzen** [comment]
Please test if this issue still occurs with the [second beta for 2.7](https://github.com/jellyfin/jellyfin-android/releases/tag/v2.7.0-beta.2) as I suspect this issue is fixed there.

**Comment by Yamus08** [comment]
> Please test if this issue still occurs with the [second beta for 2.7](https://github.com/jellyfin/jellyfin-android/releases/tag/v2.7.0-beta.2) as I suspect this issue is fixed there.

Issue resolved. Thanks for the quick fix

**Comment by nielsvanvelzen** [comment]
I wouldn't necessarily call it a "quick" fix as this issue has been open for some time. I just happened to fix a different issue earlier today and then looked at this one and suspected my fix would work here as well 😄.

Thanks for confirming, closing the issue as fixed in 2.7 then!

**Comment by ulysse31** [comment]
Hello !

Issue was closed because "quick fix" is installing the beta of 2.7 ...
But available version on fdroid or the official google app store is still affected ...
When will the 2.7 be out ? Because ... This issue is still ongoing on the "official" / "regular" version ...

**Comment by nielsvanvelzen** [comment]
The issue was closed because the issue is fixed in our master branch. Not necessarily because it's in a release. The release for 2.7 can be followed in [this discussion](https://github.com/jellyfin/jellyfin-android/discussions/2035).
