### ISSUE TITLE
Unable to access server running Jellyfin 10.8.0

### ISSUE THREAD

**Issue by Norakthes** [jellyfin/jellyfin-android#480]
**Describe the bug**
The app is unable to access a server runnng jellyfin 10.8.0
Goes between 2 different errors
1. giving an error `Tried X candidates for input, without success` where X changes depending on how the url is specified
2. giving a black screen and staying there indefinitely

**To Reproduce**
To reproduce no. 1:
1. Open app
2. Input url to server running 10.7.6
3. Close app and clear cache
4. Upgrade server to Jellyfin 10.8.0
3. Get error

To reproduce no. 2:
1. Clear all cache and userdata (if not wiped already)
2. Open app
3. Input url to server running 10.8.0
4. Black screen

**Expected behavior**
To be able to get to log in screen

**Logs**
[logcat.txt](https://github.com/jellyfin/jellyfin-android/files/6927717/logcat.txt)

**System (please complete the following information):**
 - App version: 2.3.0
 - Android version: Android 9
 - Device manufacturer and model: Nubia Z20 (NX627J)
 - Jellyfin server version: 10.8.0
 - The type of video player implementation used: default player as all userdata is blank

**Additional context**
Everything worked fine in ~~version 2.3.0-beta.6 and~~ version 2.2.3

**Comment by CarlosOlivo** [comment]
Confirmed, tested with https://demo.jellyfin.org/unstable

```
2021-08-03 21:52:10.705 5406-5406/org.jellyfin.mobile.debug I/ConnectFragment: checkServerUrlAndConnection https://demo.jellyfin.org/unstable
2021-08-03 21:52:10.711 5406-5406/org.jellyfin.mobile.debug I/ConnectFragment: Address candidates are [https://demo.jellyfin.org/unstable, https://demo.jellyfin.org:8096/unstable, https://demo.jellyfin.org:8920/unstable]
2021-08-03 21:52:10.908 5406-5406/org.jellyfin.mobile.debug I/ConnectFragment: Found valid server at https://demo.jellyfin.org/unstable with rating GREAT and version 10.8.0
2021-08-03 21:52:10.968 5406-5406/org.jellyfin.mobile.debug I/WebViewUtilsKt: WebView user agent is Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86 Build/RSR1.201013.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36, detected version is 83
2021-08-03 21:52:11.392 5406-5406/org.jellyfin.mobile.debug E/WebViewFragment$initialize: Received WebView HTTP 404 error: null
```

But I don't know if it's a server problem:
- https://demo.jellyfin.org/unstable/ -> 404 Not Found
- https://demo.jellyfin.org/unstable/web -> 404 Not Found
- https://demo.jellyfin.org/unstable/web/ -> 200 OK

**Comment by Norakthes** [comment]
I'd lean towards an issue with the app since I can still access my server running 10.8.0 on old versions of the app

**Comment by CarlosOlivo** [comment]
Are you sure your server was not updated in the transition from beta v2.3.0-beta.6 to stable v2.3.0? (~ 1.5 months ago)

I just tested with [v2.3.0-beta.6](https://github.com/jellyfin/jellyfin-android/releases/tag/v2.3.0-beta.6) from GitHub and it has the same issue

**Comment by Norakthes** [comment]
On version 2.2.3 I'm able to get access my server, but need to input the url 2 times, and get a ![different error at login](https://user-images.githubusercontent.com/30022536/128196855-f5935648-75e8-4cd9-b724-937a8f561e36.png)
But I'm able to get to my server and access my media ![Screenshot_20210804-161253.png](https://user-images.githubusercontent.com/30022536/128197010-9c16d486-b189-4cf3-8412-c3aa94852372.png)

**Comment by martadinata666** [comment]
Coming here after update from playstore, thought my jellyfin server borked. But seems it app issue.
Same problem as @Norakthes , application stay black after entering server URL, manually install ver 2.2.3 work as usuall like stated above need to add server URL twice.
```
    App version: 2.3.0
    Android version: Android 10
    Device manufacturer and model: Xiaomi Mi 6X
    Jellyfin server version: 10.8.0
```

**Comment by blackCauldron7** [comment]
Same issue but with Jellyfin 10.7.6 server and android app 2.3.0 stable

**Comment by nielsvanvelzen** [comment]
There is an issue in the unstable builds (10.8) that causes the redirect to the web client to fail. The PR that introduced this issue is likely https://github.com/jellyfin/jellyfin/pull/5803 and we're looking into it. 

Normally the redirect makes sure the webview in the app opens the web client, but now it returns a 404 response causing the app to show a connection issue. When the issue is fixed in the server the app should work again without changes in the app.

**Comment by Norakthes** [comment]
Great to hear that this is being fixed! I just find it slightly weird that v. 2.2.3 can access the server, but glad to know that the problem is being worked on!

**Comment by Maxr1998** [comment]
I think 2.2.3 had an a bit more hardcoded approach. More robust in this specific case, but generally not the best for compatibility.

**Comment by crobibero** [comment]
I just tested the redirect and it works for me without issue (redirecting `/` to `/web/index.html`)

**Comment by CarlosOlivo** [comment]
> I just tested the redirect and it works for me without issue (redirecting `/` to `/web/index.html`)

That's because some changes are required to support Jellyfin 10.8.

See #485

You can try a build with these changes [here](https://github.com/jellyfin/jellyfin-android/suites/3423834069/artifacts/81033068).

**Comment by crobibero** [comment]
I don’t have an android device. I was referring solely to the redirect, which I’ve fixed in this PR.

https://github.com/jellyfin/jellyfin/pull/6404

**Comment by CarlosOlivo** [comment]
> I don’t have an android device. I was referring solely to the redirect, which I’ve fixed in this PR.

Right, I mean that redirection is not the only problem that prevents access to Jellyfin 10.8 servers, it is also required to make another change here

Note: At the time of writing this comment https://demo.jellyfin.org/unstable still keeps throwing the 404 error, I imagine we have to wait at 06:00 EST for the snapshot to update

**Comment by nielsvanvelzen** [comment]
We've made some fixes to the server (jellyfin/jellyfin#6404) and web ui (jellyfin/jellyfin-web#2835) that should fix compatibility with 10.8. Make sure to update your unstable server build.

**Comment by Paulus88** [comment]
It seems to have started working with the latest unstable version of 10.8
20210809.58

Its working for me anyways. Thanks Jellyfin, crazy good platform by the way!

**Comment by Norakthes** [comment]
Great that the redirect is working now! I'm a little hesitant to close the issue though, because I still get this error ![IMG_20210809_230219.jpg](https://user-images.githubusercontent.com/30022536/128774402-e8df1551-ea86-43fe-a1de-550f579143e5.jpg)
Even though I get the error I can still access my media. 
I'm very happy that the issue has been dealt with, and thank all the jellyfin team for their amazing work!

**Comment by martadinata666** [comment]
confirmed working 👍

**Comment by Maxplosion** [comment]
Does not work for me with 10.7.6 (same as https://github.com/jellyfin/jellyfin-android/issues/480#issuecomment-893277972) and newest version 2.3.0 from f-droid. 
stops at "Tried X candidates for input, without success" without letting me get further. 
Works fine in last beta version before 2.3.0.

**Comment by nielsvanvelzen** [comment]
Closing since the issue with unstable 10.8 servers is fixed. The issue for F-Droid users is tracked in #493 and we're working on publishing a fix.
